image: python:latest

before_script:
  - pip install -r requirements.txt
  - pip install -e .

stages:
  - build
  - test

run_unittests:
  stage: test
  script:
    - flake8
    - python sandbox/manage.py test
